// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-xVaE_aIqyrv8PGv7ZD9wtEZoRae-lMU',
    appId: '1:1726906151:web:d94ab0d375f5e5e4413302',
    messagingSenderId: '1726906151',
    projectId: 'dummy-auth-3bbb6',
    authDomain: 'dummy-auth-3bbb6.firebaseapp.com',
    storageBucket: 'dummy-auth-3bbb6.appspot.com',
    measurementId: 'G-10MS3N2JPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEu4fb0VSbEFIRKunvBO_WYtsmJEi7Gmg',
    appId: '1:1726906151:android:e0163e340a4d0ff6413302',
    messagingSenderId: '1726906151',
    projectId: 'dummy-auth-3bbb6',
    storageBucket: 'dummy-auth-3bbb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBAicKSwzU3I7gQC7tV9Y0OQ6YNuaOuyw',
    appId: '1:1726906151:ios:24380632de73ebfe413302',
    messagingSenderId: '1726906151',
    projectId: 'dummy-auth-3bbb6',
    storageBucket: 'dummy-auth-3bbb6.appspot.com',
    iosBundleId: 'com.example.dummy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBAicKSwzU3I7gQC7tV9Y0OQ6YNuaOuyw',
    appId: '1:1726906151:ios:24380632de73ebfe413302',
    messagingSenderId: '1726906151',
    projectId: 'dummy-auth-3bbb6',
    storageBucket: 'dummy-auth-3bbb6.appspot.com',
    iosBundleId: 'com.example.dummy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-xVaE_aIqyrv8PGv7ZD9wtEZoRae-lMU',
    appId: '1:1726906151:web:ddb4ac3170f73dce413302',
    messagingSenderId: '1726906151',
    projectId: 'dummy-auth-3bbb6',
    authDomain: 'dummy-auth-3bbb6.firebaseapp.com',
    storageBucket: 'dummy-auth-3bbb6.appspot.com',
    measurementId: 'G-NSEK03VS1F',
  );
}
